// <auto-generated />
namespace Module06_TP01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_samuraiToWeapon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_samuraiToWeapon));
        
        string IMigrationMetadata.Id
        {
            get { return "202004221352150_add_samuraiToWeapon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
